from flask import (
    Flask,
    request,
    render_template,
    make_response,
    abort
)
from flask_cors import CORS

import model
import responses as res

app = Flask(
    __name__,
    static_url_path="/"
)
CORS(app)

@app.route("/")
def home():
    """Returns the website"""
    # Change to index.html
    return app.send_static_file("index.html")

@app.route("/sass/<text>")
def sass(text: str) -> dict:
    """
    []

    Parameters
    ----------
    text : str
        The input text for the ML algorithm to work on

    Returns
    -------
    json
    """
    return model.generate_response_json(text)

# The following return only one of the items generated by the above
@app.route("/sass/is_polite/<text>")
def sass_is_polite(text: str) -> bool:
    """ """
    return model.generate_response_json(text).is_polite
@app.route("/sass/prediction/<text>")
def sass_prediction(text: str) -> float:
    """ """
    return model.generate_response_json(text).prediction
@app.route("/sass/output/<text>")
def sass_output(text: str) -> str:
    """ """
    return model.generate_response_json(text).output

@app.route("/responses/all")
def responses_all() -> str:
    """Returns all responses as text"""
    #pol = Path(f"{app.static_folder}/responses/polite").read_text()
    #imp = Path(f"{app.static_folder}/responses/impolite").read_text()
    #return f"{pol}{imp}"
    return res.all_responses()

@app.route("/responses/<typ>/random")
def responses_random(typ: str) -> str:
    """
    Parameters
    ----------
    typ : str
        One of 'polite' or 'impolite'

    Returns
    -------
    str
    """
    if typ == "polite":
        return res.random_response(polite=True)
    elif typ == "impolite":
        return res.random_response(polite=False)
    else:
        # TODO: Send Error as JSON
        raise Error()
